### ISSUE TITLE
Runtime Error: Size Mismatch Error m1: [1 x 6200600], m2: [43108000 x 10] 

### ISSUE THREAD

**Issue by researStudent** [shuhao02/flsim#1]
When I ran DQN Server on CIFAR-10 dataset (In cifar-10.json.template, only changed server to:, "server": "dqn")

Complete Error as follows:
.
.
.
[INFO][21:32:06]: Training on client #98
[INFO][21:32:06]: Training on client #99
[INFO][21:36:37]: Reports recieved: 100
[INFO][21:36:37]: Training: 100 rounds or 99.0% accuracy

[INFO][21:36:37]: **** Round 1/100 ****
Traceback (most recent call last):
  File "run.py", line 50, in <module>
    main()
  File "run.py", line 43, in main
    fl_server.run()
  File "/home/abc/server/dqn.py", line 108, in run
    super().run()
  File "/home/abc/server/server.py", line 151, in run
    accuracy = self.round()
  File "/home/abc/server/dqn.py", line 114, in round
    sample_client_index = self.selection()
  File "/home/abc/server/dqn.py", line 207, in selection
    sample_client_index = self.dqn.choose_action(weights)
  File "/home/abc/server/dqn.py", line 49, in choose_action
    actions_value = self.eval_net.forward(x)
  File "/home/abc/server/dqn.py", line 258, in forward
    x = self.fc1(x)
  File "/home/abc/.conda/envs/fl-py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/abc/.conda/envs/fl-py37/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/abc/.conda/envs/fl-py37/lib/python3.7/site-packages/torch/nn/functional.py", line 1406, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [1 x 6200600], m2: [43108000 x 10] at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/TH/generic/THTensorMath.cpp:961

**Comment by wixidixi** [comment]
换了数据集后 全连接层的参数也要换
